name: Deploy to PUCMM Server Via FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Build the site
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ftps
          local-dir: ./dist/
          server-dir: /web/
          exclude: |
            **/.git*
          dangerous-clean-slate: false